force-app/main/default/objects/API_Log__c/API_Log__c.object-meta.xml
<CustomObject>
    <label>API Log</label>
    <nameField>
        <displayFormat>API-{0000}</displayFormat>
        <label>API Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Log__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/API_Log__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>API Logs</relationshipLabel>
    <relationshipName>API_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Log__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>API Logs</relationshipLabel>
    <relationshipName>API_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Log__c/fields/Requested_From__c.field-meta.xml
<CustomField>
    <fullName>Requested_From__c</fullName>
    <label>Requested From</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <color>#FF9900</color>
                <label>Open</label>
            </value>
            <value>
                <fullName>Valuator to be assigned</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>No response</fullName>
                <color>#FF6666</color>
                <label>No response</label>
            </value>
            <value>
                <fullName>Switched Off Not Reachable</fullName>
            </value>
            <value>
                <fullName>Follow up</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
                <label>Wrong number</label>
            </value>
            <value>
                <fullName>Language Issue</fullName>
            </value>
            <value>
                <fullName>Already Evaluated</fullName>
            </value>
            <value>
                <fullName>Location Not Serviceable</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Buy in Future</fullName>
            </value>
            <value>
                <fullName>Buy lead</fullName>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
            <value>
                <fullName>Dispute at dealership</fullName>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
            </value>
            <value>
                <fullName>Evaluated</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
                <color>#6666CC</color>
                <label>Finalised</label>
            </value>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Interested in CV</fullName>
            </value>
            <value>
                <fullName>Interested in New Car</fullName>
            </value>
            <value>
                <fullName>Invalid Number</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live completed</fullName>
            </value>
            <value>
                <fullName>Live deal closure</fullName>
            </value>
            <value>
                <fullName>Live follow-up</fullName>
            </value>
            <value>
                <fullName>Live rejected</fullName>
            </value>
            <value>
                <fullName>Live soldout</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Error_Records__c.field-meta.xml
<CustomField>
    <fullName>Error_Records__c</fullName>
    <label>Error Records</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
                <color>#000000</color>
                <label>Hot</label>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
            <value>
                <fullName>Test Drive</fullName>
                <color>#FF6600</color>
                <label>Test Drive</label>
            </value>
            <value>
                <fullName>Test Drive Rescheduled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#FF0000</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Warm</fullName>
                <color>#FF6600</color>
                <label>Warm</label>
            </value>
            <value>
                <fullName>Cold</fullName>
                <color>#006600</color>
                <label>Cold</label>
            </value>
            <value>
                <fullName>Not interested</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Visiting</fullName>
            </value>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
                <color>#009900</color>
                <label>Finalised</label>
            </value>
            <value>
                <fullName>No response</fullName>
                <color>#CC66CC</color>
                <label>No response</label>
            </value>
            <value>
                <fullName>Walk-in</fullName>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
            </value>
            <value>
                <fullName>Number Busy</fullName>
            </value>
            <value>
                <fullName>Invalid Number</fullName>
            </value>
            <value>
                <fullName>Interested in New Car</fullName>
            </value>
            <value>
                <fullName>Interested in CV</fullName>
            </value>
            <value>
                <fullName>Switched Off Not Reachable</fullName>
                <color>#FF6666</color>
                <label>Switched Off Not Reachable</label>
            </value>
            <value>
                <fullName>Pre-Sale Complaint</fullName>
            </value>
            <value>
                <fullName>Dispute at dealership</fullName>
            </value>
            <value>
                <fullName>Language Issue</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
                <color>#000099</color>
                <label>Sold</label>
            </value>
            <value>
                <fullName>Follow up</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <color>#FF9966</color>
                <label>Open</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Rejected by valuator</fullName>
            </value>
            <value>
                <fullName>Rejected before evaluation</fullName>
            </value>
            <value>
                <fullName>Evaluated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LogService.cls
/*
 * Class created by Deepali
 * Purpose: To provide log records for capturing exceptions and providing info about error records 
*/
public class LogService {
    
    // 14Mar2022:Asif:Start :: For capturing 
    public static String requestedFrom;
    // 14Mar2022:Asif:End

    //added by Deepali
    //Purpose: To insert log records with tag and, error message and source info
    public static void insertGenericErrorLog(Exception e,String source,String category){
       Log__c log = new Log__c();
        log.Tag__c = category;
        String msg = 'Error Message: ' + e.getMessage() + '\n LineNumber: ' + e.getLineNumber() + '\n Exception Type: ' + e.getTypeName() + '\n Cause: ' + e.getCause() + '\nStack Trace ' + e.getStackTraceString();
        log.message__c = msg;
        log.Source__c=source;
        insert log;        
    }  
    
    //added by Deepali
    //Purpose: To insert log records with tag and, error message, source and error records info
    public static void insertGenericErrorLog(Exception e,String source,String category, String errorRecords){
        Log__c log = new Log__c();
        log.Tag__c = category;
        String msg = 'Error Message: ' + e.getMessage() + '\n LineNumber: ' + e.getLineNumber() + '\n Exception Type: ' + e.getTypeName() + '\n Cause: ' + e.getCause() + '\nStack Trace ' + e.getStackTraceString();
        log.message__c = msg;
        log.Source__c=source;
        log.Error_Records__c = errorRecords;
        insert log;        
    }  
  
    
    //Purpose: To insert api log records with Endpoint, Request Body, Response Body, Status and tag info
    //For Call out
    public static void createApiLogs(String endPoint,String requestBody,String responseBody,String status,String tag){
        API_Log__c apiLog=new API_Log__c();
        apiLog.Endpoint__c= endPoint;
        apiLog.Request_Body__c=requestBody;
        apiLog.Response_Body__c=responseBody;
        if(responseBody.contains('Fail') || responseBody.contains('Error') || responseBody.contains('error') || responseBody.contains('Attempt to de-reference')){
            apiLog.Status__c= 'Failed';
        }else{
            apiLog.Status__c= 'Success';
        }
        apiLog.Tag__c = tag;
        apiLog.Requested_From__c = requestedFrom; // 14Mar2022:Asif :: For capturing IP of Client

        Database.DMLOptions dmo = new Database.DMLOptions();
		dmo.allowFieldTruncation = true;
        System.debug('LogService.createApiLogs apiLog :: ' + apiLog);
		Database.insert(apiLog, dmo);
      //  insert apiLog;
    }
    
    
    public static API_Log__c createApiLogs(String endPoint,String requestBody,String responseBody,String status,String tag,String leadId,Boolean isInsert){
        System.debug('LogService.createApiLogs :: ');
        List<API_Log__c> apiInsertList = new List<Api_Log__c>();
        API_Log__c apiLog=new API_Log__c();
        if(leadId !=null) {
            if(leadId.startsWith('00Q')) {
                apiLog.Lead__c = leadId;
                system.debug('leadId'+leadId);
                system.debug('This is lead Id');
            } else if(leadId.startsWith('006')) {
                apiLog.Opportunity__c = leadId;
                system.debug('OppId'+leadId);
                system.debug('This is Opportunity Id');
            }
        }

        apiLog.Endpoint__c= endPoint;
        apiLog.Request_Body__c=requestBody;
        apiLog.Response_Body__c=responseBody;
        if((responseBody.contains('Fail') || responseBody.contains('Error') || responseBody.contains('error') || responseBody.contains('Attempt to de-reference')) && status == null){
            apiLog.Status__c= 'Failed';
        }else{
            apiLog.Status__c= status;
        }
        apiLog.Tag__c = tag;
        apiLog.Requested_From__c = requestedFrom; // 14Mar2022:Asif :: For capturing IP of Client
        
        System.debug('apiLog.Lead__c :' + apiLog.Lead__c);
        System.debug('apiLog.Opportunity__c :' + apiLog.Opportunity__c);
        if(isInsert){
            apiInsertList.add(apiLog);
            createApiLogs(apiInsertList);
        } else {
            return apiLog;
        }
        return apiLog;
    }  
    
    public static Api_Log__c createApiLogs(String failedRec, String Status, String tag){
        Api_Log__c api = new Api_Log__c();
        api.Response_Body__c = failedRec;
        api.Status__c = 'Failed';
        api.Tag__c = tag;
        return api;
    }
    
    //Added By Aravindan
    public static void createApiLogs(List<API_Log__c>  ApiList){
        System.debug('inserting into DB apiLog.size :'+ ApiList.size());
        System.debug('Logs : ' + ApiList);
        if(ApiList.size() > 0){
            Database.insert(ApiList,False);
            System.debug('_APILog_INSERTED_');
        }
    }
    
}