force-app/main/default/objects/API_Log__c/API_Log__c.object-meta.xml
<CustomObject>
    <label>API Log</label>
    <nameField>
        <displayFormat>API-{0000}</displayFormat>
        <label>API Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CnB_Endpoint__c/CnB_Endpoint__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CnB Endpoint</label>
</CustomObject>

force-app/main/default/objects/CnB_Endpoint__c/fields/BuyerToCnBEndpoint__c.field-meta.xml
<CustomField>
    <fullName>BuyerToCnBEndpoint__c</fullName>
    <label>BuyerToCnBEndpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CnB_Endpoint__c/fields/x_app_api_key__c.field-meta.xml
<CustomField>
    <fullName>x_app_api_key__c</fullName>
    <label>x-app-api-key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CnB_Endpoint__c/fields/x_app_api_secret__c.field-meta.xml
<CustomField>
    <fullName>x_app_api_secret__c</fullName>
    <label>x-app-api-secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <color>#FF9900</color>
                <label>Open</label>
            </value>
            <value>
                <fullName>Valuator to be assigned</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>No response</fullName>
                <color>#FF6666</color>
                <label>No response</label>
            </value>
            <value>
                <fullName>Switched Off Not Reachable</fullName>
            </value>
            <value>
                <fullName>Follow up</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
                <label>Wrong number</label>
            </value>
            <value>
                <fullName>Language Issue</fullName>
            </value>
            <value>
                <fullName>Already Evaluated</fullName>
            </value>
            <value>
                <fullName>Location Not Serviceable</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Buy in Future</fullName>
            </value>
            <value>
                <fullName>Buy lead</fullName>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
            <value>
                <fullName>Dispute at dealership</fullName>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
            </value>
            <value>
                <fullName>Evaluated</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
                <color>#6666CC</color>
                <label>Finalised</label>
            </value>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Interested in CV</fullName>
            </value>
            <value>
                <fullName>Interested in New Car</fullName>
            </value>
            <value>
                <fullName>Invalid Number</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live completed</fullName>
            </value>
            <value>
                <fullName>Live deal closure</fullName>
            </value>
            <value>
                <fullName>Live follow-up</fullName>
            </value>
            <value>
                <fullName>Live rejected</fullName>
            </value>
            <value>
                <fullName>Live soldout</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EcomCallout.cls
public class EcomCallout {
    
    public static boolean allowCallout = false;
    
    public class RequestWrapper{
        public String lead_status;
        public String sfdc_lead_id;
        public DateTime followup_date;
        public String followup_comments;
    }

    @future(callout = true)
    public static void ecomLeads(Set<Id> leadIds){
        System.debug('EcomCallout.ecomLeads::');
        String responseStr;
        String requestStr;
        String endPoint;
        Integer httpStatusCode;
        String sfId;
       
        HttpResponse res = new HttpResponse();
        try {
            List<Lead> lea = [Select id, Status__c, LastName,Follow_Up_Date_Time__c,FollowUp_Comments__c from lead where Id IN :leadIds];
            sfId = lea[0].Id;
            
            // creating request body
            RequestWrapper reqWrap = new RequestWrapper();
            reqWrap.lead_status = lea[0].Status__c;
            reqWrap.sfdc_lead_id = lea[0].Id;
            reqWrap.followup_date = lea[0].Follow_Up_Date_Time__c;
            reqWrap.followup_comments = lea[0].FollowUp_Comments__c;
            requestStr = JSON.serialize(reqWrap);
            
            // collecting credentails from 
            CnB_Endpoint__c cnbEndpoint = CnB_Endpoint__c.getAll().values();
            String username = cnbEndpoint.Username__c; 
            String password = cnbEndpoint.Password__c;
            endPoint = cnbEndpoint.BuyerToCnBEndpoint__c;
            // Add basic authentication to header
            // Create blob of user:pass
            Blob headerValue = Blob.valueOf(username + ':' + password);
            // Base 64 Encode the blob and prepend "Basic "
            String authorizationHeader = 'Basic ' + EncodingUtil.base64Encode(headerValue);
            // Add the basic auth string to the Request Header
            HttpRequest req = new HttpRequest();
            // Configure standard headers
          
            // This tells the API that we are sending and receiving the data as a JSON object 
            // adding headers
            req.setHeader('Accept', '*/*');
            req.setHeader('Content-Type', 'application/json');
            req.setHeader('x-app-api-key', cnbEndpoint.x_app_api_key__c);
            req.setHeader('x-app-api-secret', cnbEndpoint.x_app_api_secret__c);
            req.setHeader('Authorization', authorizationHeader);
            
            req.setMethod('POST');
            req.setEndpoint(endPoint);
            req.setTimeout(120000);
            req.setBody(requestStr);
            
            http h = new http();
            res = h.send(req);
            httpStatusCode = res.getStatusCode();
            responseStr = res.getBody();
            
            System.debug('Request ' + requestStr);
            System.debug('Response ' + responseStr);
            
        } catch(Exception e) {
            httpStatusCode = 500;
            System.debug('Caught Exception: ' + e);
            String exceptionMsg;
            String statusMsg = 'Failed';
            if(e.getMessage().contains('Read timed out') && e.getTypeName().contains('System.CalloutException')) {
                exceptionMsg = 'SFDC waited for the response from CNB Server for 120 seconds and didn\'t  get the Response.'; 
            } else {
                exceptionMsg = 'EXCEPTION: Type: ' + e.getTypeName() + ', Message: ' +  e.getMessage() + ' at Line: ' + e.getLineNumber();
            }
            responseStr = exceptionMsg;
        } finally {
            List<Api_Log__c> apiLogs = new List<Api_Log__c>();
            String apiLogStatus = httpStatusCode == 200 ? 'Success' : 'Failed';
            apiLogs.add(LogService.createApiLogs(endPoint, requestStr, responseStr, apiLogStatus, 'EcomCnB', sfId, false));
            if(!apiLogs.isEmpty()){
                LogService.createApiLogs(apiLogs);
            }
            LeadTriggerHelper.apiFired = true;
        }
    }
}