force-app/main/default/objects/API_Log__c/API_Log__c.object-meta.xml
<CustomObject>
    <label>API Log</label>
    <nameField>
        <displayFormat>API-{0000}</displayFormat>
        <label>API Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <color>#FF9900</color>
                <label>Open</label>
            </value>
            <value>
                <fullName>Valuator to be assigned</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>No response</fullName>
                <color>#FF6666</color>
                <label>No response</label>
            </value>
            <value>
                <fullName>Switched Off Not Reachable</fullName>
            </value>
            <value>
                <fullName>Follow up</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
                <label>Wrong number</label>
            </value>
            <value>
                <fullName>Language Issue</fullName>
            </value>
            <value>
                <fullName>Already Evaluated</fullName>
            </value>
            <value>
                <fullName>Location Not Serviceable</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Buy in Future</fullName>
            </value>
            <value>
                <fullName>Buy lead</fullName>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
            <value>
                <fullName>Dispute at dealership</fullName>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
            </value>
            <value>
                <fullName>Evaluated</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
                <color>#6666CC</color>
                <label>Finalised</label>
            </value>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Interested in CV</fullName>
            </value>
            <value>
                <fullName>Interested in New Car</fullName>
            </value>
            <value>
                <fullName>Invalid Number</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live completed</fullName>
            </value>
            <value>
                <fullName>Live deal closure</fullName>
            </value>
            <value>
                <fullName>Live follow-up</fullName>
            </value>
            <value>
                <fullName>Live rejected</fullName>
            </value>
            <value>
                <fullName>Live soldout</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
                <color>#000000</color>
                <label>Hot</label>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
            <value>
                <fullName>Test Drive</fullName>
                <color>#FF6600</color>
                <label>Test Drive</label>
            </value>
            <value>
                <fullName>Test Drive Rescheduled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#FF0000</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Warm</fullName>
                <color>#FF6600</color>
                <label>Warm</label>
            </value>
            <value>
                <fullName>Cold</fullName>
                <color>#006600</color>
                <label>Cold</label>
            </value>
            <value>
                <fullName>Not interested</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Visiting</fullName>
            </value>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
                <color>#009900</color>
                <label>Finalised</label>
            </value>
            <value>
                <fullName>No response</fullName>
                <color>#CC66CC</color>
                <label>No response</label>
            </value>
            <value>
                <fullName>Walk-in</fullName>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
            </value>
            <value>
                <fullName>Number Busy</fullName>
            </value>
            <value>
                <fullName>Invalid Number</fullName>
            </value>
            <value>
                <fullName>Interested in New Car</fullName>
            </value>
            <value>
                <fullName>Interested in CV</fullName>
            </value>
            <value>
                <fullName>Switched Off Not Reachable</fullName>
                <color>#FF6666</color>
                <label>Switched Off Not Reachable</label>
            </value>
            <value>
                <fullName>Pre-Sale Complaint</fullName>
            </value>
            <value>
                <fullName>Dispute at dealership</fullName>
            </value>
            <value>
                <fullName>Language Issue</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
                <color>#000099</color>
                <label>Sold</label>
            </value>
            <value>
                <fullName>Follow up</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <color>#FF9966</color>
                <label>Open</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Rejected by valuator</fullName>
            </value>
            <value>
                <fullName>Rejected before evaluation</fullName>
            </value>
            <value>
                <fullName>Evaluated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ElisionActivityCalloutServiceBatchTest.cls
@isTest
public class ElisionActivityCalloutServiceBatchTest {
    @isTest
    public static void executeTest() {
        lead l = new lead();
        l.ACM_Name__c = 'test';
        l.Phone = '9876543220';
        l.LeadSource = 'Other';
        insert l;
        Opportunity o = new Opportunity();
            o.Name = 'test';
            o.StageName = 'Proposal';
            o.CloseDate = system.today();
            insert o;
        API_Log__c a = new API_Log__c();
        a.Status__c = 'Exception Occurred';
        insert a;
        
        Task tas = new task();
        tas.WhoId = l.Id;
       // tas.WhatId = o.Id;
        tas.API_Log__c = a.Id;
        insert tas;
        test.startTest();
        ElisionActivityCalloutServiceBatch obj = new ElisionActivityCalloutServiceBatch();
        //ElisionActivityCalloutServiceBatch.getNextScheduleTime();
        database.executeBatch(obj);

        
         test.stopTest();
    }

    @isTest
    public static void setSchedule() {
        Test.startTest();
          ElisionActivityCalloutServiceBatch testsche = new ElisionActivityCalloutServiceBatch();
		String sch = '0 0 15 * * ?';
		system.schedule('Test status Check', sch, testsche );
        
         test.stopTest();
    }

}