force-app/main/default/objects/API_Log__c/API_Log__c.object-meta.xml
<CustomObject>
    <label>API Log</label>
    <nameField>
        <displayFormat>API-{0000}</displayFormat>
        <label>API Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Log__c/fields/Failed_Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Failed_Retry_Count__c</fullName>
    <label>Failed Retry Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/API_Log__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>API Logs</relationshipLabel>
    <relationshipName>API_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
                <color>#000000</color>
                <label>Hot</label>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
            <value>
                <fullName>Test Drive</fullName>
                <color>#FF6600</color>
                <label>Test Drive</label>
            </value>
            <value>
                <fullName>Test Drive Rescheduled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#FF0000</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Warm</fullName>
                <color>#FF6600</color>
                <label>Warm</label>
            </value>
            <value>
                <fullName>Cold</fullName>
                <color>#006600</color>
                <label>Cold</label>
            </value>
            <value>
                <fullName>Not interested</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Visiting</fullName>
            </value>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
                <color>#009900</color>
                <label>Finalised</label>
            </value>
            <value>
                <fullName>No response</fullName>
                <color>#CC66CC</color>
                <label>No response</label>
            </value>
            <value>
                <fullName>Walk-in</fullName>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
            </value>
            <value>
                <fullName>Number Busy</fullName>
            </value>
            <value>
                <fullName>Invalid Number</fullName>
            </value>
            <value>
                <fullName>Interested in New Car</fullName>
            </value>
            <value>
                <fullName>Interested in CV</fullName>
            </value>
            <value>
                <fullName>Switched Off Not Reachable</fullName>
                <color>#FF6666</color>
                <label>Switched Off Not Reachable</label>
            </value>
            <value>
                <fullName>Pre-Sale Complaint</fullName>
            </value>
            <value>
                <fullName>Dispute at dealership</fullName>
            </value>
            <value>
                <fullName>Language Issue</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
                <color>#000099</color>
                <label>Sold</label>
            </value>
            <value>
                <fullName>Follow up</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <color>#FF9966</color>
                <label>Open</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Rejected by valuator</fullName>
            </value>
            <value>
                <fullName>Rejected before evaluation</fullName>
            </value>
            <value>
                <fullName>Evaluated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RetryleadPushToLMSOppBatchTest.cls
@isTest
public class RetryleadPushToLMSOppBatchTest {
    @isTest
    public static void testAll() {
        
        Opportunity o = new Opportunity();
        o.Name = 'test';
        o.StageName = 'Proposal';
        o.CloseDate = system.today();
        insert o;
        
        
        
        API_Log__c apiLog = new API_Log__c();
        apiLog.Opportunity__c = o.Id;
        apiLog.Status__c = 'AUTH_ENDPOINT_ERROR';
        apiLog.Tag__c = 'BUC LMS Opp Callout';
        apiLog.Failed_Retry_Count__c = null;
        
        insert apiLog;
        
        
        
        Test.startTest();
        RetryleadPushToLMSOppBatch batchJob = new RetryleadPushToLMSOppBatch();
        ID batchProcessId = Database.executeBatch(batchJob);
        Test.stopTest();
    }
    
    @isTest
    static void testScheduledTrigger() {
        // Schedule the job
        Test.startTest();
        Datetime currentTime = System.now();
        String cronExp = '0 1 * * * ?';
        System.schedule('TestRetryleadPushToLMSoppBatch', cronExp, new RetryleadPushToLMSOppBatch());
        Test.stopTest();

    }
 
}