force-app/main/default/objects/API_Log__c/API_Log__c.object-meta.xml
<CustomObject>
    <label>API Log</label>
    <nameField>
        <displayFormat>API-{0000}</displayFormat>
        <label>API Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Log__c/fields/Failed_Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Failed_Retry_Count__c</fullName>
    <label>Failed Retry Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/API_Log__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>API Logs</relationshipLabel>
    <relationshipName>API_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <color>#FF9900</color>
                <label>Open</label>
            </value>
            <value>
                <fullName>Valuator to be assigned</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>No response</fullName>
                <color>#FF6666</color>
                <label>No response</label>
            </value>
            <value>
                <fullName>Switched Off Not Reachable</fullName>
            </value>
            <value>
                <fullName>Follow up</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
                <label>Wrong number</label>
            </value>
            <value>
                <fullName>Language Issue</fullName>
            </value>
            <value>
                <fullName>Already Evaluated</fullName>
            </value>
            <value>
                <fullName>Location Not Serviceable</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Buy in Future</fullName>
            </value>
            <value>
                <fullName>Buy lead</fullName>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
            <value>
                <fullName>Dispute at dealership</fullName>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
            </value>
            <value>
                <fullName>Evaluated</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
                <color>#6666CC</color>
                <label>Finalised</label>
            </value>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Interested in CV</fullName>
            </value>
            <value>
                <fullName>Interested in New Car</fullName>
            </value>
            <value>
                <fullName>Invalid Number</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live completed</fullName>
            </value>
            <value>
                <fullName>Live deal closure</fullName>
            </value>
            <value>
                <fullName>Live follow-up</fullName>
            </value>
            <value>
                <fullName>Live rejected</fullName>
            </value>
            <value>
                <fullName>Live soldout</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RetryleadPushToLMSBatch.cls
global class RetryleadPushToLMSBatch implements database.Batchable<sObject>, Database.AllowsCallouts,Schedulable{
    
    global void execute(SchedulableContext ctx){
        RetryleadPushToLMSBatch eobj = new RetryleadPushToLMSBatch();
        Database.executeBatch(eobj, 50);   
    } 
    
    global Database.QueryLocator Start(Database.BatchableContext BC){
        
        return Database.getQueryLocator([Select id,Lead__c, Status__c, Tag__c,Failed_Retry_Count__c from API_Log__c Where Status__c IN ('AUTH_ENDPOINT_ERROR','INSERT_ENDPOINT_ERROR') AND Lead__c != null AND Tag__c = 'BUC LMS Lead Callout' AND Failed_Retry_Count__c = null AND CreatedDate = LAST_N_DAYS:2 LIMIT 1]);
    }
    
    
    global void execute(Database.BatchableContext BC, List<API_Log__c> newList){
        
        List<API_Log__c> apList = new List<API_Log__c>();
        
        List<Id> leadId = new List<Id>();
        List<Id> oppId = new List<Id>();
        
        for(API_Log__c apiLog : newList) {   
            
            
            if(apiLog.Lead__c != null){
                
                leadId.add(apiLog.Lead__c);
            }
            
            
        }
        System.debug('listLeadId -->'+leadId);
        
        if(!leadId.isEmpty()){
            LeadPushToLMS.pushLeadsToLms(new List<Id>(leadId));
        }
       
        
        // api log update
        for (API_Log__c api : [Select id,Lead__c,Failed_Retry_Count__c from API_Log__c Where Lead__c  =:leadId] ){
            //system.debug('__finish___');
            
            API_log__c ap = new API_log__c();
            ap.Id =  api.id;
            system.debug('Failed_Retry_Count__c ::::' +api.Failed_Retry_Count__c);
            If(api.Failed_Retry_Count__c == null ){
                ap.Failed_Retry_Count__c = 1; 
            }
            
            apList.add(ap);
            
        }
        system.debug('apList::::' +apList);
        update apList;
        
        
    }
    
    
    global void finish(Database.BatchableContext BC){
        
        
    }
    
}