force-app/main/default/objects/GupShup_Endpoints__c/GupShup_Endpoints__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>GupShup Endpoints</label>
</CustomObject>

force-app/main/default/objects/GupShup_Endpoints__c/fields/Single_Message_Api_Key__c.field-meta.xml
<CustomField>
    <fullName>Single_Message_Api_Key__c</fullName>
    <label>Single Message Api Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GupShup_Endpoints__c/fields/Single_Message_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Single_Message_Endpoint__c</fullName>
    <label>Single Message Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/RP_Dealer__c/RP_Dealer__c.object-meta.xml
<CustomObject>
    <label>RP Dealer</label>
    <nameField>
        <label>RP Dealer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RP Dealers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Log__c/SMS_Log__c.object-meta.xml
<CustomObject>
    <label>SMS Log</label>
    <nameField>
        <displayFormat>SLN-{0000}</displayFormat>
        <label>SMS Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Log__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SMS Logs</relationshipLabel>
    <relationshipName>SMS_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_Log__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>SMS Logs</relationshipLabel>
    <relationshipName>SMS_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_Log__c/fields/RP_Dealer__c.field-meta.xml
<CustomField>
    <fullName>RP_Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RP Dealer</label>
    <referenceTo>RP_Dealer__c</referenceTo>
    <relationshipLabel>SMS Logs</relationshipLabel>
    <relationshipName>SMS_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_Log__c/fields/SMS_Body__c.field-meta.xml
<CustomField>
    <fullName>SMS_Body__c</fullName>
    <label>SMS Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SMS_Log__c/fields/SMS_Template__c.field-meta.xml
<CustomField>
    <fullName>SMS_Template__c</fullName>
    <label>SMS Template</label>
    <referenceTo>SMS_Template__c</referenceTo>
    <relationshipLabel>SMS Logs</relationshipLabel>
    <relationshipName>SMS_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SMS_Template__c/SMS_Template__c.object-meta.xml
<CustomObject>
    <label>SMS Template</label>
    <nameField>
        <label>SMS Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Template__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SMS_Template__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy Used Car</fullName>
            </value>
            <value>
                <fullName>Sell Used Car</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Buy Used Car Warranty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS_Template__c/fields/SMS_Body__c.field-meta.xml
<CustomField>
    <fullName>SMS_Body__c</fullName>
    <label>SMS Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SMS_Template__c/fields/Trigger_Object__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Object__c</fullName>
    <label>Trigger Object</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Qualified Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SMSDisplayControllerTestClass.cls
@isTest
public class SMSDisplayControllerTestClass {
    
    public static testmethod void getTemplateTest()
    {
        
        Map<Id,SMS_Log__c> mapSmsLog = new Map<Id,SMS_Log__c>();
        Set<Id> leadId = new Set<Id>();
        
        Lead l = new Lead();
        l.LastName = 'test';
        l.Phone = '8123565656';
        l.LeadSource = 'Other';
        insert l;
        leadId.add(l.Id);
            
        SMS_Template__c S = new SMS_Template__c();
        S.Name = 'Quote Creation';
        S.Module__c = 'Sell Used Car';
        S.SMS_Body__c = 'this is sms template {!lead.lastname}';
        S.Trigger_Object__c = 'Lead';
        S.IsActive__c = true;
        insert S;
        
        Set<Id> oppId = new Set<Id>();
        Opportunity op = new Opportunity();
        op.lead__c = l.Id;
        op.Name = l.LastName;
        op.Phone__c =  l.Phone;
        op.LeadSource = l.LeadSource;
        op.StageName = 'New';
        op.CloseDate = system.today();
        insert op;
        oppId.add(op.Id) ;
        
        Account acc = new Account();
        acc.LastName = 'test';
        acc.RecordTypeId = AccountConstants.customerAccountRecordTypeId;
        insert acc;
        
        Contact co = new Contact();
        co.LastName = l.LastName;
        co.Phone = l.Phone;
        co.AccountId = l.Customer__c;
        insert co;
        
        Rp_Dealer__c rp =  new Rp_Dealer__c();
        rp.Name = 'test';
        insert rp;
        
       SMS_Log__c smsLog = new SMS_Log__c();
        smsLog.SMS_Body__c = '{! Test, your purchase of CertiFirst for vehicle  is successful! Please click on the link to view the warranty booklet For any other queries, please reach us on 18004194800Mahindra First Choice';
        smsLog.SMS_Template__c = S.Id;
        smsLog.Dealer__c = acc.Id;
        smsLog.Rp_Dealer__c = rp.Id;
        insert smsLog; 
        mapSmsLog.put(smsLog.Id,smsLog);
        
        GupShup_Endpoints__c G = new GupShup_Endpoints__c();
        G.Name ='abc';
        G.Password__c = 'abc';
        G.UserId__c = '123';
        G.Single_Message_Api_Key__c = 'avcd';
        G.Single_Message_Endpoint__c ='https://enterprise.smsgupshup.com/GatewayAPI/rest';
        insert G; 
        
        test.startTest();
        Test.setMock(HttpCalloutMock.class, new GupShupTestMock());
        SMSLogService.sendParametersToUser(mapSmsLog);
        SMSLogService.sendSMS('test123',smsLog.Id);
        
        LeadSelector.getAllLeadData(leadId);
        OpportunitySelector.getAllOpportunityData(oppId);
        SMSDisplayController.getTemplate(l.Id);
        SMSDisplayController.getTemplate(S.Id);
        SMSDisplayController.getTemplate(op.Id);
        SMSDisplayController.getContacts(op.Id);
        SMSDisplayController.getContacts(l.Id);
        SMSDisplayController.getContacts(co.Id);
        SMSDisplayController.createSMSLog(l.id, S.id,'test', '1234567890');
        SMSDisplayController.createSMSLog(op.id, S.id,'test', '1234567890');
        test.stopTest();
        
    }

}