force-app/main/default/objects/SMS_Log__c/SMS_Log__c.object-meta.xml
<CustomObject>
    <label>SMS Log</label>
    <nameField>
        <displayFormat>SLN-{0000}</displayFormat>
        <label>SMS Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Log__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>SMS Logs</relationshipLabel>
    <relationshipName>SMS_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SMSLogSelector.cls
public class SMSLogSelector {

    public static List<SMS_Log__c> getSMSLogData(set<Id> smsLogIds){
        
        System.debug('smsLogIds' + smsLogIds);
        Map<String, Schema.SObjectField> fieldMap = SMS_Log__c.sObjectType.getDescribe().fields.getMap();
        System.debug('fieldMap' + fieldMap);
        List<String> fieldNames = new List<String>();
        for(String s : fieldMap.keySet()){
            fieldNames.add(s);
        }
        System.debug('fieldNames' + fieldNames);
		String soqlQuery = ' SELECT ' + string.join(fieldNames, ',') + ',Lead__r.Phone FROM  SMS_Log__c Where Id =: smsLogIds';
        System.debug('Query'+soqlQuery);
        return Database.query(soqlQuery);
    }
}