force-app/main/default/objects/Elision_Campaign__c/Elision_Campaign__c.object-meta.xml
<CustomObject>
    <label>Elision Campaign</label>
    <nameField>
        <label>Elision Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Elision Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Elision_Campaign__c/fields/Campaign_Id_NWH__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Id_NWH__c</fullName>
    <label>Campaign Id NWH</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Elision_Campaign__c/fields/Campaign_Id_WH__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Id_WH__c</fullName>
    <label>Campaign Id WH</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Elision_Campaign__c/fields/CampaignId_FollowUp__c.field-meta.xml
<CustomField>
    <fullName>CampaignId_FollowUp__c</fullName>
    <label>CampaignId FollowUp</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Elision_Campaign__c/fields/Elision_Campaign_Category__c.field-meta.xml
<CustomField>
    <fullName>Elision_Campaign_Category__c</fullName>
    <label>Elision Campaign Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ecomm Reservation</fullName>
            </value>
            <value>
                <fullName>Ecomm TestDrive</fullName>
            </value>
            <value>
                <fullName>Ecomm PaymentFailed</fullName>
            </value>
            <value>
                <fullName>Superstore M2All - North</fullName>
            </value>
            <value>
                <fullName>Superstore M2All - West</fullName>
            </value>
            <value>
                <fullName>Superstore M2All - South</fullName>
            </value>
            <value>
                <fullName>General BUC - South</fullName>
            </value>
            <value>
                <fullName>General BUC - Others</fullName>
            </value>
            <value>
                <fullName>HI Procurement</fullName>
            </value>
            <value>
                <fullName>Inspection Report Download</fullName>
            </value>
            <value>
                <fullName>Thane Motors Superstore</fullName>
            </value>
            <value>
                <fullName>HI ICO eligible</fullName>
            </value>
            <value>
                <fullName>Microsite Kerala</fullName>
            </value>
            <value>
                <fullName>Microsite Non Kerala</fullName>
            </value>
            <value>
                <fullName>NCR Cluster - Microsite</fullName>
            </value>
            <value>
                <fullName>Kerala Cluster - Microsite</fullName>
            </value>
            <value>
                <fullName>Maharashtra Cluster - Microsite</fullName>
            </value>
            <value>
                <fullName>NCR Cluster</fullName>
            </value>
            <value>
                <fullName>Kerala Cluster</fullName>
            </value>
            <value>
                <fullName>Maharashtra Cluster</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Elision_Campaign__c/fields/Lead_Flag__c.field-meta.xml
<CustomField>
    <fullName>Lead_Flag__c</fullName>
    <label>Lead Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PaymentPending</fullName>
            </value>
            <value>
                <fullName>Reserve</fullName>
            </value>
            <value>
                <fullName>uc_testdrive</fullName>
            </value>
            <value>
                <fullName>PaymentFailed</fullName>
            </value>
            <value>
                <fullName>inspection report</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Elision_Campaign__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MFC - Chatbot</fullName>
            </value>
            <value>
                <fullName>Exotel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Elision_Campaign__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Test Drive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Elision_Campaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Test Drive</fullName>
            </value>
            <value>
                <fullName>Test Drive Scheduled</fullName>
            </value>
            <value>
                <fullName>Payment Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HiServiceableCity__c/HiServiceableCity__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Hi Serviceable City</label>
</CustomObject>

force-app/main/default/objects/Lead/fields/Lead_Flag__c.field-meta.xml
<CustomField>
    <fullName>Lead_Flag__c</fullName>
    <label>Lead Flag</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>Reserve</fullName>
            </value>
            <value>
                <fullName>new</fullName>
            </value>
            <value>
                <fullName>inspection report</fullName>
            </value>
            <value>
                <fullName>uc_testdrive</fullName>
            </value>
            <value>
                <fullName>getseller</fullName>
            </value>
            <value>
                <fullName>quickloan</fullName>
            </value>
            <value>
                <fullName>PaymentFailed</fullName>
            </value>
            <value>
                <fullName>non_ico_journey_completed</fullName>
            </value>
            <value>
                <fullName>ico_journey_pending</fullName>
            </value>
            <value>
                <fullName>non_ico_journey_completed_user_dropped</fullName>
            </value>
            <value>
                <fullName>ico_journey_pending_user_dropped</fullName>
            </value>
            <value>
                <fullName>ico_journey_completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <color>#FF9900</color>
                <label>Open</label>
            </value>
            <value>
                <fullName>Valuator to be assigned</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>No response</fullName>
                <color>#FF6666</color>
                <label>No response</label>
            </value>
            <value>
                <fullName>Switched Off Not Reachable</fullName>
            </value>
            <value>
                <fullName>Follow up</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
                <label>Wrong number</label>
            </value>
            <value>
                <fullName>Language Issue</fullName>
            </value>
            <value>
                <fullName>Already Evaluated</fullName>
            </value>
            <value>
                <fullName>Location Not Serviceable</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Buy in Future</fullName>
            </value>
            <value>
                <fullName>Buy lead</fullName>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
            <value>
                <fullName>Dispute at dealership</fullName>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
            </value>
            <value>
                <fullName>Evaluated</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
                <color>#6666CC</color>
                <label>Finalised</label>
            </value>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Interested in CV</fullName>
            </value>
            <value>
                <fullName>Interested in New Car</fullName>
            </value>
            <value>
                <fullName>Invalid Number</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live completed</fullName>
            </value>
            <value>
                <fullName>Live deal closure</fullName>
            </value>
            <value>
                <fullName>Live follow-up</fullName>
            </value>
            <value>
                <fullName>Live rejected</fullName>
            </value>
            <value>
                <fullName>Live soldout</fullName>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Interested - Hot</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/ELV.recordType-meta.xml
<RecordType>
    <fullName>ELV</fullName>
    <active>true</active>
    <businessProcess>ELV Lead Process</businessProcess>
    <label>ELV</label>
</RecordType>

force-app/main/default/classes/ElisonLeadActivityService.cls
public class ElisonLeadActivityService {
    public static void init(List<Lead> newList, Map<Id, Lead> oldMap) {
        
        ElisonLeadActivityService ELAServiceObj = new ElisonLeadActivityService();
        ELAServiceObj.start(newList, oldMap);
        
    } 
    public void start(List<Lead> newList, Map<Id, Lead> oldMap) {
        //for eligibles campaigns
        Set<String> categoryList = new Set<String>();
        //list for new lead
        List<Lead> lead1=new List<Lead>();
        
        // Business hour check
        DateTime elisionDueDate;
        Boolean isInBusinessHour;
        Set<Id> leadId = new Set<Id>();
        Set<String> phone = new Set<String>();
        
        Map<String, Lead> elisionLeadMap = new Map<String, Lead>();
        
        //for custom setting record 
        List<String> cityList = new List<String>();
        List<HiServiceableCity__c> hiServiceableCityList = [Select City__c from HiServiceableCity__c];
        for(HiServiceableCity__c hsc : hiServiceableCityList) {
            cityList.add(hsc.city__c.toLowerCase());
        }
        
        for(Lead lRec : newList) {
            
            phone.add(lRec.Phone);
            leadId.add(lRec.Id);
            
            Lead lRec1 = new Lead( Id = lRec.id);
            
            String keyStr = lRec.RecordTypeId + '-' + lRec.HI_Serviceable__c + '-' + lRec.CTIDuplicate__c;
            System.debug('Lea Status'+lRec.RecordTypeId +' '+lRec.HI_Serviceable__c+' '+lRec.CTIDuplicate__c + ' '+lRec.Seller_City__c);
            //12-06-2025:Sachin:CRM:1312: Start:ELV_Lead_Source campaign
            if (lRec.RecordTypeId == LeadConstants.ElvLeadRecordTypeId && lRec.LeadSource == 'ELV') {
                System.debug('Lea Status'+lRec);
                categoryList.add('ELV Lead source'); 
            }
            //CRM:1312:End:ELV_Lead_Source campaign
            //18-06-2025:Sachin:CRM:1316: Start:PI campaign
            else if(lRec.RecordTypeId == LeadConstants.ElvLeadRecordTypeId && lRec.LeadSource == 'PI') {
                System.debug('Lea Status'+lRec);
                categoryList.add('Premium Inspection'); 
            }
            //CRM:1316:End:PI campaign
            else if( lRec.RecordTypeId == LeadConstants.SellerLeadRecordTypeId && lRec.HI_Serviceable__c == '1' && lRec.CTIDuplicate__c ==false && lRec.Seller_City__c !=null && cityList.contains(lRec.Seller_City__c.toLowerCase()) )
            {
                System.debug('Lea Status'+lRec);
                if((lRec.Status__c=='Open' || lRec.Status__c==null )&&(lRec.Status =='New'|| lRec.Status =='Open'||lRec.Status =='Follow Up'|| lRec.Status ==null ) )
                {
                    if(lRec.ICO_eligible_flag__c)            //04-APR-2023: Sachin: CRM::1126: Start
                    {
                        if(lRec.Lead_Flag__c == 'non_ico_journey_completed_user_dropped' || lRec.Lead_Flag__c == 'ico_journey_pending_user_dropped' || lRec.Lead_Flag__c == 'ico_journey_completed'){
                        categoryList.add('HI Procurement');   
                        }  
                    }
                    else{
                        categoryList.add('HI Procurement');
                        }  									  //04-APR-2023: Sachin: CRM::1126: End
                }
            }
            
            System.debug('Category: '+categoryList);
            
            elisionLeadMap.put(keyStr, lRec);
        }
        
        
        //Fetch Related Leads
        
        List<Lead> relatedLead = new List<Lead>();
        
        Map<Id,Id> relatedLeadId = new Map<Id,Id>();
        relatedLead = [Select Id, customer__C  from Lead where Phone IN :phone and Id Not IN :leadId];
        for(Lead lea : relatedLead){
            relatedLeadId.put(lea.Id,lea.customer__C);
        }
        
        Set<Id> relatedOpenLeadId = new Set<Id>();
        Set<Id> relatedAccountId = new Set<Id>();
        
        List<Task> taskRec = [Select Id, WhoId, AccountId from Task where WhoId IN :relatedLeadId.keySet() And Status = 'Open'  ];
        for(Task tRec1 : taskRec)
        {
            relatedOpenLeadId.add(tRec1.AccountId);
            relatedAccountId.add(relatedLeadId.get(tRec1.WhoId));
        }
        
        
        // Working hours
        DateTime businessStartTime = Datetime.newInstanceGMT(System.now().year(), System.now().month(), System.now().day(), 3, 30, 0);
        DateTIme businessEndTime = businessStartTime.addHours(11);  //10-JAN-2024: Sachin: CRM::1224: Changed the business working time 
        DateTime nextWorkingHourDT = businessStartTime.addDays(1);
        DateTime nextWorkingHourD = nextWorkingHourDT.addMinutes(-60* 12); // today end time
        
        // for Task insert       
        List<Task> taskToInsertArr = new List<Task>();
        //for Lead update
        List<Lead> lRecToUpdateArr = new List<Lead>();
        
        // fetching eligibles campaigns
        Map<String, Elision_Campaign__c> elisionCampaignMatchedMap = new Map<String, Elision_Campaign__c>();
        
        // querying campaings
        List<Elision_Campaign__c> elisionCampaignDBArr = [SELECT Id, Name, Lead_Flag__c, Lead_Source__c, Status__c, Stage__c, Elision_Campaign_Category__c, Campaign_Id_NWH__c, Campaign_Id_WH__c, CampaignId_FollowUp__c FROM Elision_Campaign__c WHERE Elision_Campaign_Category__c In :categoryList ];
        System.debug('elisionCampaignDBArr ' + elisionCampaignDBArr);
        for(Elision_Campaign__c ecRec : elisionCampaignDBArr) {
            
            //String keyStr = ecRec.RecordType + '-' + ecRec.HI_Serviceable__c + '-' + ecRec.CTIDuplicate__c;
            
            elisionCampaignMatchedMap.put(ecRec.Elision_Campaign_Category__c, ecRec);
        }
        System.debug('elisionCampaignMatchedMap ' + elisionCampaignMatchedMap);
        
        for(Lead lRec : newList){
            
            if(relatedAccountId.contains(lRec.Customer__c))
            {
                continue;
            }
            
            Lead lRec1 = new Lead( Id = lRec.id);
            String keyStr = '';
            //12-06-2025:Sachin:CRM:1312: Start:ELV_Lead_Source campaign
            if ( lRec.RecordTypeId == LeadConstants.ElvLeadRecordTypeId && lRec.LeadSource == 'ELV') {
                lRec1.Elision_Campaign_category__c ='ELV Lead source';
                keyStr = 'ELV Lead source';
                lead1.add(lRec1);
            }
            //CRM:1312:End:ELV_Lead_Source campaign
            //18-06-2025:Sachin:CRM:1316: Start:PI campaign
            else if(lRec.RecordTypeId == LeadConstants.ElvLeadRecordTypeId && lRec.LeadSource == 'PI') {
                lRec1.Elision_Campaign_category__c ='Premium Inspection';
                keyStr = 'Premium Inspection';
                lead1.add(lRec1); 
            }
            //CRM:1316:End:PI campaign
            else if( lRec.RecordTypeId == LeadConstants.SellerLeadRecordTypeId && lRec.HI_Serviceable__c == '1' && lRec.CTIDuplicate__c ==false && lRec.Seller_City__c !=null && cityList.contains(lRec.Seller_City__c.toLowerCase()) )
            {
                if((lRec.Status__c=='Open' || lRec.Status__c==null )&&(lRec.Status =='New'|| lRec.Status =='Open'||lRec.Status =='Follow Up'|| lRec.Status == null ) )
                {
                    if(lRec.ICO_eligible_flag__c)        //04-APR-2023: Sachin: CRM::1126: Start
                    {
                        if(lRec.Lead_Flag__c == 'non_ico_journey_completed_user_dropped' || lRec.Lead_Flag__c == 'ico_journey_pending_user_dropped' || lRec.Lead_Flag__c == 'ico_journey_completed'){
                         lRec1.Elision_Campaign_category__c ='HI Procurement';
                         keyStr = 'HI Procurement';
                         lead1.add(lRec1);
                         }   
                    } 
                    else{
                        lRec1.Elision_Campaign_category__c ='HI Procurement';
                        keyStr = 'HI Procurement';
                        lead1.add(lRec1);
                        } 								//04-APR-2023: Sachin: CRM::1126: End
                } 
            }
            
            if(!elisionCampaignMatchedMap.containsKey(keyStr)) 
            {
                continue;
            }
            Elision_Campaign__c ecRec = elisionCampaignMatchedMap.get(keyStr);
            
            //DateTime elisionDueDate;
            // Business hour check
            //Boolean isInBusinessHour;
            //Boolean followUp;        
            
            System.debug('CreatedDate > '+lRec.CreatedDate);
            System.debug('businessStartTime > '+businessStartTime);
            System.debug('businessEndTime > '+businessEndTime);
            if(lRec.CreatedDate >= businessStartTime && lRec.CreatedDate <= businessEndTime) { // In Businness Hour
                
                isInBusinessHour = true;
                // followUp = false;
                elisionDueDate = lRec.CreatedDate.addMinutes(15);
            }
            else { // out Business Hour
                
                isInBusinessHour = false;
                //followUp = false;
                elisionDueDate = lRec.CreatedDate >= nextWorkingHourD ? businessStartTime : nextWorkingHourDT;
                elisionDueDate = elisionDueDate.addHours(1);
                
            }
            
            system.debug('IsInBusines: '+isInBusinessHour);
            //system.debug('IsInBusines: '+followUp);
            
            // if matched create 
            //  create Task
            Task tRec = new Task();       
            tRec.WhoId = lRec.Id;
            tRec.Elision_Campaign__c = ecRec.Id;
            tRec.Campaign_Id__c = isInBusinessHour ? ecRec.Campaign_Id_WH__c : ecRec.Campaign_Id_NWH__c;
            tRec.Campaign_Name__c = ecRec.Name;
            tRec.Subject = 'Elision BUC Call';
            tRec.Elision_Due_Date__c = elisionDueDate;
            tRec.RecordTypeId = Schema.getGlobalDescribe().get('Task').getDescribe().getRecordTypeInfosByDeveloperName().get('Elision').getRecordTypeId();
            taskToInsertArr.add(tRec);
            
            system.debug('taskToInsertArr' +taskToInsertArr); 
            lRecToUpdateArr.add(lRec1);
        }//end for loop
        
        // Task insert
        if(!taskToInsertArr.isEmpty()) {
            insert taskToInsertArr;
        }
        System.debug('lRecToUpdateArr ' + lRecToUpdateArr);
        
        // lead update
        if(!lRecToUpdateArr.isEmpty()) {
            update lRecToUpdateArr;
        }
        
        
    }
}