force-app/main/default/objects/CnB_Endpoint__c/CnB_Endpoint__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CnB Endpoint</label>
</CustomObject>

force-app/main/default/objects/CnB_Endpoint__c/fields/BuyerToCnBEndpoint__c.field-meta.xml
<CustomField>
    <fullName>BuyerToCnBEndpoint__c</fullName>
    <label>BuyerToCnBEndpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CnB_Endpoint__c/fields/x_app_api_key__c.field-meta.xml
<CustomField>
    <fullName>x_app_api_key__c</fullName>
    <label>x-app-api-key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CnB_Endpoint__c/fields/x_app_api_secret__c.field-meta.xml
<CustomField>
    <fullName>x_app_api_secret__c</fullName>
    <label>x-app-api-secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Flag__c.field-meta.xml
<CustomField>
    <fullName>Lead_Flag__c</fullName>
    <label>Lead Flag</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>Reserve</fullName>
            </value>
            <value>
                <fullName>new</fullName>
            </value>
            <value>
                <fullName>inspection report</fullName>
            </value>
            <value>
                <fullName>uc_testdrive</fullName>
            </value>
            <value>
                <fullName>getseller</fullName>
            </value>
            <value>
                <fullName>quickloan</fullName>
            </value>
            <value>
                <fullName>PaymentFailed</fullName>
            </value>
            <value>
                <fullName>non_ico_journey_completed</fullName>
            </value>
            <value>
                <fullName>ico_journey_pending</fullName>
            </value>
            <value>
                <fullName>non_ico_journey_completed_user_dropped</fullName>
            </value>
            <value>
                <fullName>ico_journey_pending_user_dropped</fullName>
            </value>
            <value>
                <fullName>ico_journey_completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <color>#FF9900</color>
                <label>Open</label>
            </value>
            <value>
                <fullName>Valuator to be assigned</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>No response</fullName>
                <color>#FF6666</color>
                <label>No response</label>
            </value>
            <value>
                <fullName>Switched Off Not Reachable</fullName>
            </value>
            <value>
                <fullName>Follow up</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
                <label>Wrong number</label>
            </value>
            <value>
                <fullName>Language Issue</fullName>
            </value>
            <value>
                <fullName>Already Evaluated</fullName>
            </value>
            <value>
                <fullName>Location Not Serviceable</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Buy in Future</fullName>
            </value>
            <value>
                <fullName>Buy lead</fullName>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
            <value>
                <fullName>Dispute at dealership</fullName>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
            </value>
            <value>
                <fullName>Evaluated</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
                <color>#6666CC</color>
                <label>Finalised</label>
            </value>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Interested in CV</fullName>
            </value>
            <value>
                <fullName>Interested in New Car</fullName>
            </value>
            <value>
                <fullName>Invalid Number</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live completed</fullName>
            </value>
            <value>
                <fullName>Live deal closure</fullName>
            </value>
            <value>
                <fullName>Live follow-up</fullName>
            </value>
            <value>
                <fullName>Live rejected</fullName>
            </value>
            <value>
                <fullName>Live soldout</fullName>
            </value>
            <value>
                <fullName>Test Drive</fullName>
            </value>
            <value>
                <fullName>Reserve</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EcomCallout_Test.cls
@isTest


public class EcomCallout_Test {
    
    public static testmethod void getEcomCallOutInfoTest()
    {
        Test.setMock(HttpCalloutMock.class, new EcomCalloutMock());
        Test.setMock(HttpCalloutMock.class, new LeadPushtoLMSMock());
        
        Set<Id> leaIds = new Set<Id>();
        
        CnB_Endpoint__c cnb = new CnB_Endpoint__c();
        cnb.BuyerToCnBEndpoint__c = 'test';
        cnb.Name = 'test';
        cnb.Password__c = 'test pass';
        cnb.Username__c = 'test uname';
        cnb.x_app_api_key__c = '123';
        cnb.x_app_api_secret__c = 'test';
        insert cnb;
        
        Lead lea = new Lead();
        Lea.RecordTypeId = LeadConstants.buyerLeadRecordTypeId;
        lea.LastName = 'Test lead';
        lea.Phone = '9538017402';
        lea.Lead_Flag__c = 'Reserve';
        lea.Status__c = 'Cold';
        lea.Follow_Up_Date_Time__c = System.now()+1;
        lea.FollowUp_Comments__c = 'test';
        lea.LeadSource = 'Advertisement';
        insert lea;
        
        lea.Status__c = 'Test Drive';
        //update lea;
        
        leaIds.add(lea.Id);
        
        
         test.startTest();
       	 EcomCallout.ecomLeads(leaIds);
         test.stopTest(); 
        
    }
    

}