force-app/main/default/objects/CnB_Endpoint__c/CnB_Endpoint__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CnB Endpoint</label>
</CustomObject>

force-app/main/default/objects/CnB_Endpoint__c/fields/CreateNewLead__c.field-meta.xml
<CustomField>
    <fullName>CreateNewLead__c</fullName>
    <label>CreateNewLead</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CnB_Endpoint__c/fields/LeadStatusChange__c.field-meta.xml
<CustomField>
    <fullName>LeadStatusChange__c</fullName>
    <label>LeadStatusChange</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CnB_Endpoint__c/fields/NewBike_LeadStatus__c.field-meta.xml
<CustomField>
    <fullName>NewBike_LeadStatus__c</fullName>
    <label>NewBike LeadStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CnB_Endpoint__c/fields/NewBike_NewLead__c.field-meta.xml
<CustomField>
    <fullName>NewBike_NewLead__c</fullName>
    <label>NewBike NewLead</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CnB_Endpoint__c/fields/x_app_api_key__c.field-meta.xml
<CustomField>
    <fullName>x_app_api_key__c</fullName>
    <label>x-app-api-key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CnB_Endpoint__c/fields/x_app_api_secret__c.field-meta.xml
<CustomField>
    <fullName>x_app_api_secret__c</fullName>
    <label>x-app-api-secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <color>#FF9900</color>
                <label>Open</label>
            </value>
            <value>
                <fullName>Valuator to be assigned</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>No response</fullName>
                <color>#FF6666</color>
                <label>No response</label>
            </value>
            <value>
                <fullName>Switched Off Not Reachable</fullName>
            </value>
            <value>
                <fullName>Follow up</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
                <label>Wrong number</label>
            </value>
            <value>
                <fullName>Language Issue</fullName>
            </value>
            <value>
                <fullName>Already Evaluated</fullName>
            </value>
            <value>
                <fullName>Location Not Serviceable</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Buy in Future</fullName>
            </value>
            <value>
                <fullName>Buy lead</fullName>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
            <value>
                <fullName>Dispute at dealership</fullName>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
            </value>
            <value>
                <fullName>Evaluated</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
                <color>#6666CC</color>
                <label>Finalised</label>
            </value>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Interested in CV</fullName>
            </value>
            <value>
                <fullName>Interested in New Car</fullName>
            </value>
            <value>
                <fullName>Invalid Number</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live completed</fullName>
            </value>
            <value>
                <fullName>Live deal closure</fullName>
            </value>
            <value>
                <fullName>Live follow-up</fullName>
            </value>
            <value>
                <fullName>Live rejected</fullName>
            </value>
            <value>
                <fullName>Live soldout</fullName>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Interested - Cold</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Didnot pickup</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CnBRecommendationTest.cls
@isTest
public class CnBRecommendationTest {

    public static testmethod void test1(){
        CnB_Endpoint__c cnb = new CnB_Endpoint__c();
        cnb.Name = 'cnb';
        cnb.LeadStatusChange__c = 'www.test.com';
        cnb.NewBike_LeadStatus__c = 'www.test.com';
        cnb.NewBike_NewLead__c = 'www.test.com';
        cnb.x_app_api_key__c = 'test';
        cnb.x_app_api_secret__c = 'test';
        cnb.Username__c = 'test';
        cnb.Password__c = 'test';
        cnb.CreateNewLead__c = 'www.test.com';
        insert cnb;
        
        Lead lea = new Lead();
        lea.LastName = 'test';
        lea.Phone = '9538017609';
        lea.Email = 'soumya@gmail.com';
        lea.Form_Type_Id__c = '4';
        lea.RecordTypeId = LeadConstants.CnBLeadRecordTypeId;
        lea.Car_Model_Id__c = '1517';
        lea.Status__c = '9';
        lea.Area_City__c = 'bglore';
        insert lea;
        
        String S = '[{"check":true,"id_car_model":"1562","manufacturer_name":"Tata","max_mileage":"24.00","max_price":"669990","min_mileage":"24.00","min_price":"669990","model_name":"Tiago JTP","rating":"7.5","status":"1"}]';
        test.startTest();
        Test.setMock(HttpCalloutMock.class, new httpMockForReccommendation());
        CnBLeadWrapperClass.CnBResponseData rec = CnBRecommendationController.getCarRecommendations(lea.id);
        CnBRecommendationController.createLead(s, lea.Id, 'cross-sell');
        Lead lead1 = CnBRecommendationController.returnLead(lea.Id);
        test.stopTest();
    }
    
    public static testmethod void test2(){
        CnB_Endpoint__c cnb = new CnB_Endpoint__c();
        cnb.Name = 'cnb';
        cnb.LeadStatusChange__c = 'www.test.com';
        cnb.NewBike_LeadStatus__c = 'www.test.com';
        cnb.NewBike_NewLead__c = 'www.test.com';
        cnb.x_app_api_key__c = 'test';
        cnb.x_app_api_secret__c = 'test';
        cnb.Username__c = 'test';
        cnb.Password__c = 'test';
        cnb.CreateNewLead__c = 'www.test.com';
        insert cnb;
        
        Lead lea = new Lead();
        lea.LastName = 'test';
        lea.Phone = '9538017609';
        lea.Email = 'soumya@gmail.com';
        lea.Form_Type_Id__c = '4';
        lea.RecordTypeId = LeadConstants.CnBLeadRecordTypeId;
        lea.Car_Model_Id__c = '1517';
        lea.Status__c = '9';
        lea.Area_City__c = 'bglore';
        insert lea;
        
        test.startTest();
        Test.setMock(HttpCalloutMock.class, new httpMockForCarSearch());
        List<CnBLeadWrapperClass.CnBCalloutResponseData> search =  CnBRecommendationController.searchRecommendations('maruti', lea.Id);
        test.stopTest();
    }
}