force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <externalId>true</externalId>
    <label>Branch Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Email__c/Email__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Email</label>
</CustomObject>

force-app/main/default/objects/Email__c/fields/Person_Email__c.field-meta.xml
<CustomField>
    <fullName>Person_Email__c</fullName>
    <label>Person Email</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Executive__c/Executive__c.object-meta.xml
<CustomObject>
    <label>Executive</label>
    <nameField>
        <label>Executive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Executives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Executive__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Executives</relationshipLabel>
    <relationshipName>Executives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Executive__c/fields/Executive_Id__c.field-meta.xml
<CustomField>
    <fullName>Executive_Id__c</fullName>
    <externalId>true</externalId>
    <label>Executive Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fin_MMFSL__c/Fin_MMFSL__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>for MMFSL Callout end points</description>
    <label>Fin MMFSL</label>
</CustomObject>

force-app/main/default/objects/Fin_MMFSL__c/fields/client_id__c.field-meta.xml
<CustomField>
    <fullName>client_id__c</fullName>
    <label>client id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fin_MMFSL__c/fields/subscriber_code__c.field-meta.xml
<CustomField>
    <fullName>subscriber_code__c</fullName>
    <label>subscriber code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Finance_Auth_Details__c/Finance_Auth_Details__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Finance Auth Details</label>
</CustomObject>

force-app/main/default/objects/Finance_Auth_Details__c/fields/EndPoint_for_Finance_Lead_Data__c.field-meta.xml
<CustomField>
    <fullName>EndPoint_for_Finance_Lead_Data__c</fullName>
    <label>EndPoint_for_Finance_Lead_Data</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Finance_Auth_Details__c/fields/NonQualified_R2W_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>NonQualified_R2W_Endpoint__c</fullName>
    <label>NonQualified R2W Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <color>#FF9900</color>
                <label>Open</label>
            </value>
            <value>
                <fullName>Valuator to be assigned</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>No response</fullName>
                <color>#FF6666</color>
                <label>No response</label>
            </value>
            <value>
                <fullName>Switched Off Not Reachable</fullName>
            </value>
            <value>
                <fullName>Follow up</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
                <label>Wrong number</label>
            </value>
            <value>
                <fullName>Language Issue</fullName>
            </value>
            <value>
                <fullName>Already Evaluated</fullName>
            </value>
            <value>
                <fullName>Location Not Serviceable</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Buy in Future</fullName>
            </value>
            <value>
                <fullName>Buy lead</fullName>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
            <value>
                <fullName>Dispute at dealership</fullName>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
            </value>
            <value>
                <fullName>Evaluated</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
                <color>#6666CC</color>
                <label>Finalised</label>
            </value>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Interested in CV</fullName>
            </value>
            <value>
                <fullName>Interested in New Car</fullName>
            </value>
            <value>
                <fullName>Invalid Number</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live completed</fullName>
            </value>
            <value>
                <fullName>Live deal closure</fullName>
            </value>
            <value>
                <fullName>Live follow-up</fullName>
            </value>
            <value>
                <fullName>Live rejected</fullName>
            </value>
            <value>
                <fullName>Live soldout</fullName>
            </value>
            <value>
                <fullName>More Info</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FinanceLeadCallout_Test.cls
@isTest
public class FinanceLeadCallout_Test {
    
    @isTest 
    public static void getFinanceLeadInfoTest() {
		
        
        
		Email__c mail = new Email__c();
        mail.Name = 'test Email';
		mail.Person_Email__c = 'test@test.co';
        insert mail;
        
        Finance_Auth_Details__c fin = new Finance_Auth_Details__c();
        fin.Username__c = 'test';
        fin.Password__c = 'test';
        fin.Name = 'test';
        fin.Endpoint__c = 'ibbAuth';
        fin.NonQualified_R2W_Endpoint__c = 'nonQualify';
        fin.EndPoint_for_Finance_Lead_Data__c = 'ibb';
        insert fin;
        
        // mmfsl
        Fin_MMFSL__c f = new Fin_MMFSL__c();
        f.Name = 'test Fin_MMFSL__c';
        f.endpoint__c = 'mmfsl';
        f.client_id__c = 'test client Id';
        f.subscriber_code__c = 'test subscriber code';
        insert f;
        
        Branch__c b = new Branch__c();
        b.Name = 'Bangalore Branch';
        b.Branch_Code__c = '0907';
        insert b;
        
        
        Executive__c e = new Executive__c();
        e.Branch__c = b.id;
        e.Name = 'Sam';
        e.Executive_Id__c = '12765';
        insert e;
        
        Set<Id> leadIds = new Set<Id>();
        
        lead l = new lead();
        l.Branch_Related__c = b.id;
        l.Executive_Related__c = e.Id;
        l.firstName = 'Test';
        l.LastName = 'Purnima';
        l.Phone = '8989878788';
        l.MFCW_Id__c = '123987';
        l.Status__c = 'More Info';
        l.RecordTypeId = LeadConstants.financeLeadRecordTypeId;
        l.LeadSource = 'R2W';
        l.Lead_For__c = 'BLM';
        l.Exe_Id__c = '234123';
        l.Seller_State__c = 'Karnataka';
        l.Given_For__c = 'Refinance';
        l.cc_remarks__c = 'Test test';
        l.First_Contacted_Date__c = System.now();
        insert l;
        
        List<Lead> leads = new List<Lead>();
        leads.add(l);
        leadIds.add(l.Id);
        
        l.Status__c = 'Hot';
        update l;
        
        leads.add(l);
        
      //  Test.setMock(HttpCalloutMock.class, new Test_FinHTTPMock.mockAll());
                
        List<Lead> leadList = new List<Lead>();
        leadList.add(l);
        test.startTest();
        
        //FinanceLeadCallout.requestHandler('GET', ';', '',2000);
        
        //FinanceLeadCallout.pushNonQualifiedR2WLeads(leadIds);
        FinanceLeadCallout.notifyError('functionName', 'customMsg');
        
        //FinanceLeadCallout.getMMFSLLeadDetails(leadList);
        
        f.endpoint__c = 'mmfslFail';
        update f;
        
        
        
        fin.EndPoint_for_Finance_Lead_Data__c = 'ibbFail';
        update fin;
        
        l.Status__c = 'Cold';
		CheckRecursiveTrigger.callMMFSL = true;
        CheckRecursiveTrigger.callIBB = true;
        update l;
        
        FinanceLeadCallout.requestHandler('test123','test123','test123',10);
        //FinanceLeadCallout.getMMFSLLeadDetails(leadList);
        
        test.stopTest();  
    }
}