force-app/main/default/objects/Exotel_Call_Summary__c/Exotel_Call_Summary__c.object-meta.xml
<CustomObject>
    <label>Exotel Call Summary</label>
    <nameField>
        <displayFormat>ECS-{0000}</displayFormat>
        <label>Exotel Call Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exotel Call Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/CallFrom__c.field-meta.xml
<CustomField>
    <fullName>CallFrom__c</fullName>
    <label>CallFrom</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/CallSid__c.field-meta.xml
<CustomField>
    <fullName>CallSid__c</fullName>
    <externalId>true</externalId>
    <label>CallSid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/CallTo__c.field-meta.xml
<CustomField>
    <fullName>CallTo__c</fullName>
    <label>CallTo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/CallType__c.field-meta.xml
<CustomField>
    <fullName>CallType__c</fullName>
    <label>CallType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/DialWhomNumber__c.field-meta.xml
<CustomField>
    <fullName>DialWhomNumber__c</fullName>
    <label>DialWhomNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Exotel Call Summaries</relationshipLabel>
    <relationshipName>Exotel_Call_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/Legs_0_Number__c.field-meta.xml
<CustomField>
    <fullName>Legs_0_Number__c</fullName>
    <label>Legs[0][Number]</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/OutgoingPhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>OutgoingPhoneNumber__c</fullName>
    <label>OutgoingPhoneNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExotelAuthDetails__c/ExotelAuthDetails__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ExotelAuthDetails</label>
</CustomObject>

force-app/main/default/objects/Lead/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <color>#FF9900</color>
                <label>Open</label>
            </value>
            <value>
                <fullName>Valuator to be assigned</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>No response</fullName>
                <color>#FF6666</color>
                <label>No response</label>
            </value>
            <value>
                <fullName>Switched Off Not Reachable</fullName>
            </value>
            <value>
                <fullName>Follow up</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
                <label>Wrong number</label>
            </value>
            <value>
                <fullName>Language Issue</fullName>
            </value>
            <value>
                <fullName>Already Evaluated</fullName>
            </value>
            <value>
                <fullName>Location Not Serviceable</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Buy in Future</fullName>
            </value>
            <value>
                <fullName>Buy lead</fullName>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
            <value>
                <fullName>Dispute at dealership</fullName>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
            </value>
            <value>
                <fullName>Evaluated</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
                <color>#6666CC</color>
                <label>Finalised</label>
            </value>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Interested in CV</fullName>
            </value>
            <value>
                <fullName>Interested in New Car</fullName>
            </value>
            <value>
                <fullName>Invalid Number</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live completed</fullName>
            </value>
            <value>
                <fullName>Live deal closure</fullName>
            </value>
            <value>
                <fullName>Live follow-up</fullName>
            </value>
            <value>
                <fullName>Live rejected</fullName>
            </value>
            <value>
                <fullName>Live soldout</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Buyer_Used_Car.recordType-meta.xml
<RecordType>
    <fullName>Buyer_Used_Car</fullName>
    <active>true</active>
    <businessProcess>Buyer Used Car Lead Process</businessProcess>
    <label>Buyer Used Car</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
                <color>#000000</color>
                <label>Hot</label>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
            <value>
                <fullName>Test Drive</fullName>
                <color>#FF6600</color>
                <label>Test Drive</label>
            </value>
            <value>
                <fullName>Test Drive Rescheduled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#FF0000</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Warm</fullName>
                <color>#FF6600</color>
                <label>Warm</label>
            </value>
            <value>
                <fullName>Cold</fullName>
                <color>#006600</color>
                <label>Cold</label>
            </value>
            <value>
                <fullName>Not interested</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Visiting</fullName>
            </value>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
                <color>#009900</color>
                <label>Finalised</label>
            </value>
            <value>
                <fullName>No response</fullName>
                <color>#CC66CC</color>
                <label>No response</label>
            </value>
            <value>
                <fullName>Walk-in</fullName>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
            </value>
            <value>
                <fullName>Number Busy</fullName>
            </value>
            <value>
                <fullName>Invalid Number</fullName>
            </value>
            <value>
                <fullName>Interested in New Car</fullName>
            </value>
            <value>
                <fullName>Interested in CV</fullName>
            </value>
            <value>
                <fullName>Switched Off Not Reachable</fullName>
                <color>#FF6666</color>
                <label>Switched Off Not Reachable</label>
            </value>
            <value>
                <fullName>Pre-Sale Complaint</fullName>
            </value>
            <value>
                <fullName>Dispute at dealership</fullName>
            </value>
            <value>
                <fullName>Language Issue</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
                <color>#000099</color>
                <label>Sold</label>
            </value>
            <value>
                <fullName>Follow up</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <color>#FF9966</color>
                <label>Open</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Rejected by valuator</fullName>
            </value>
            <value>
                <fullName>Rejected before evaluation</fullName>
            </value>
            <value>
                <fullName>Evaluated</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ExotelCallSummaryTestClass.cls
@isTest
public class ExotelCallSummaryTestClass {
    @isTest
    public static void ExotelTest()
    {
        String exotelOutGoingPhone = '8888777766';
        Id buyerLeadRecordTypeId = Schema.getGlobalDescribe().get('Lead').getDescribe().getRecordTypeInfosByDeveloperName().get('Buyer_Used_Car').getRecordTypeId();
        String dealerRTId = AccountConstants.dealerAccountRecordTypeId;
        Account acc = new Account();
        acc.Name = 'test';
        acc.Exotel_Landing_Number__c = exotelOutGoingPhone;
        acc.BillingState = 'test';
        acc.RecordTypeId = dealerRTId;
        insert acc;

        Test.setMock(HttpCalloutMock.class, new MockHttpGenerator());
        List<Exotel_Call_Summary__c> Elist = new List<Exotel_Call_Summary__c>();
        List<Exotel_Call_Summary__c> Elist2 = new List<Exotel_Call_Summary__c>();
        Map<Id,Exotel_Call_Summary__c> mapExotel = new Map<Id,Exotel_Call_Summary__c>();
        Set<Id> exotelId = new Set<Id>();
        List<Id> lstId = new List<Id>();
        Exotel_Call_Summary__c E = new Exotel_Call_Summary__c();
        Exotel_Call_Summary__c E1 = new Exotel_Call_Summary__c();
        
        E.CallFrom__c = '9538017400';
        E.CallSid__c  = '6149bc6e965454f07c958465484a16ab';
        E.CallType__c = 'completed';
        E.CallTo__c = '9999999990';
        E.From__c = '9538017400';
        E.To__c = '8888777766';
        E.OutgoingPhoneNumber__c = exotelOutGoingPhone;
        E.Tenant_Id__c = '16184';
        E.Legs_0_Number__c = '02250111909';
        Elist.add(E);
        insert Elist;
        lstId.add(Elist[0].Id);
        exotelId.add(Elist[0].Id);
        mapExotel.put(Elist[0].Id,E);
        
        
      /*  E1.CallFrom__c = '9538017400';
        E1.CallSid__c  = '1234';
        E1.CallType__c = 'Exotel Missed';
        E1.CallTo__c = '9999999990';
        E1.From__c = '9538017400';
        E1.To__c = '8888777766';
        E1.OutgoingPhoneNumber__c = '8888777766';
        E1.Tenant_Id__c = '16184';
        E1.Legs_0_Number__c = '02250111909';
        Elist2.add(E1);
        insert Elist2;*/

        /*Exotel_Call_Summary__c E1 = new Exotel_Call_Summary__c();
        E1.CallFrom__c = '9538017406';
        E1.CallSid__c  = '12345';
        E1.CallType__c = 'completed';
        E1.CallTo__c = '9999999997';
        E1.From__c = '8123565656';
        E1.DialWhomNumber__c = '09930037047';
        E.To__c = '8888777766';
        insert E1; */
        
        
        
        Lead l = new Lead();
        l.LastName = 'test';
        l.Phone = Elist[0].CallFrom__c;
        l.LeadSource = 'Exotel';
        l.Exotel_Repeat__c = false;
        l.State = 'test';
        l.Status__c = 'test';
        l.Status = 'test';
        l.RecordTypeId = buyerLeadRecordTypeId;
        insert l;
        
       
        
       
        List<Opportunity> lstOpp = new List<Opportunity>();
        opportunity opp = new Opportunity();
        opp.name = 'test OPP';
        opp.Dealer_Phone__c = exotelOutGoingPhone;
        opp.Exotel_Call__c = Elist[0].Id;
        opp.LeadSource = 'Exotel';
        opp.Dealer__c = acc.Id;
        opp.Status__c = 'New';
        opp.Exotel_Repeat__c = false;
        opp.Customer_Phone__c = Elist[0].From__c;
        opp.Lead__c = l.id;
        opp.StageName = 'New';
        opp.CloseDate = date.today();
        lstOpp.add(opp);
        insert opp;
        
        ExotelAuthDetails__c objExotelAuth = new ExotelAuthDetails__c();
        objExotelAuth.username__c = 'Test123';
        objExotelAuth.password__c = 'testg123';
        objExotelAuth.Name = 'teszt123';
        insert objExotelAuth;
        
        List<Exotel_Call_Summary__c> Elist1 = [SELECT OutgoingPhoneNumber__c,From__c,CallFrom__c,Tenant_Id__c FROM Exotel_Call_Summary__c WHERE CallFrom__c ='9538017400'];
        for(Exotel_Call_Summary__c objExotel:Elist1) {
            objExotel.OutgoingPhoneNumber__c = '8888777767';
        }
        update Elist1;
		test.startTest();
        ExotelCallSummaryTriggerHelper.createLeadRecord(Elist);
        ExotelCallSummaryTriggerHelper.callExotelCallout(exotelId);
        ExotelCallSummaryTriggerHandler.callHelper(lstId);
        ExotelCallSummaryTriggerHandler.onAfterUpdate(Elist,mapExotel);
        
		test.stopTest();        
        
       //Opportunity opp2 = [select id,name,Dealer_Phone__c, Exotel_Call__c,dealer__r.Exotel_Landing_Number__c, Status__c,Dealer__c, Exotel_Repeat__c,Customer_Phone__c,Lead__c from Opportunity where Dealer__c IN :Acc.Id AND Status__c != 'Sold' AND Status__c != 'Lost' AND dealer__r.Exotel_Landing_Number__c != NULL AND dealer__r.Exotel_Landing_Number__c IN :E.OutgoingPhoneNumber__c AND Customer_Phone__c =:E.From__c];
        //    system.debug('opp2: '+opp2);
        //Elist.add(E);
        // Elist.add(E1);      
        /*      
    for(Opportunity o : [
        select id,name,Dealer_Phone__c, Exotel_Call__c,dealer__r.Exotel_Landing_Number__c, 
        Status__c,Dealer__c, Exotel_Repeat__c,Customer_Phone__c,Lead__c 
        from Opportunity 
        where Dealer__c IN :AccId 
        AND Status__c != 'Sold' 
        AND Status__c != 'Lost' 
        AND dealer__r.Exotel_Landing_Number__c != NULL 
        AND dealer__r.Exotel_Landing_Number__c IN :dealerPhones 
        AND Customer_Phone__c != null 
        AND Customer_Phone__c IN :customerPhones]){*/
        
        
    }
    


public class MockHttpGenerator implements HttpCalloutMock {
    // Implement this interface method
    public HTTPResponse respond(HTTPRequest req) {
        // Optionally, only send a mock response for a specific endpoint
        // and method.
        
        // Create a fake response
        HttpResponse res = new HttpResponse();
        res.setHeader('Content-Type', 'application/json');
        res.setBody('{"Call":{"Sid":"6149bc6e965454f07c958465484a16ab","ParentCallSid":"","DateCreated":"2022-10-11 09:56:20","DateUpdated":"2022-10-11 10:00:11","AccountSid":"mahindra7","To":"02250111909","From":"07588425495","PhoneNumberSid":"09513881992","Status":"completed","StartTime":"2022-10-11 09:56:20","EndTime":"2022-10-11 09:58:47","Duration":"147","Price":"2.050000","Direction":"inbound","AnsweredBy":"human","ForwardedFrom":"","CallerName":"","Uri":"v1Accountsmahindra7Calls6149bc6e965454f07c958465484a16ab","RecordingUrl":"https:s3-ap-southeast-1.amazonaws.comexotelrecordingsmahindra76149bc6e965454f07c958465484a16ab.mp3"}}');
        res.setStatusCode(200);
        return res;
    }
}
}