force-app/main/default/objects/Exotel_Call_Summary__c/Exotel_Call_Summary__c.object-meta.xml
<CustomObject>
    <label>Exotel Call Summary</label>
    <nameField>
        <displayFormat>ECS-{0000}</displayFormat>
        <label>Exotel Call Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exotel Call Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/CallFrom__c.field-meta.xml
<CustomField>
    <fullName>CallFrom__c</fullName>
    <label>CallFrom</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/CallSid__c.field-meta.xml
<CustomField>
    <fullName>CallSid__c</fullName>
    <externalId>true</externalId>
    <label>CallSid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/CallTo__c.field-meta.xml
<CustomField>
    <fullName>CallTo__c</fullName>
    <label>CallTo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/CallType__c.field-meta.xml
<CustomField>
    <fullName>CallType__c</fullName>
    <label>CallType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/CurrentTime__c.field-meta.xml
<CustomField>
    <fullName>CurrentTime__c</fullName>
    <label>CurrentTime</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/DialCallDuration__c.field-meta.xml
<CustomField>
    <fullName>DialCallDuration__c</fullName>
    <label>DialCallDuration</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/DialCallStatus__c.field-meta.xml
<CustomField>
    <fullName>DialCallStatus__c</fullName>
    <label>DialCallStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/DialWhomNumber__c.field-meta.xml
<CustomField>
    <fullName>DialWhomNumber__c</fullName>
    <label>DialWhomNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <label>EndTime</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/Legs_0_Cause__c.field-meta.xml
<CustomField>
    <fullName>Legs_0_Cause__c</fullName>
    <label>Legs[0][Cause]</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/Legs_0_CauseCode__c.field-meta.xml
<CustomField>
    <fullName>Legs_0_CauseCode__c</fullName>
    <label>Legs[0][CauseCode]</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/Legs_0_Number__c.field-meta.xml
<CustomField>
    <fullName>Legs_0_Number__c</fullName>
    <label>Legs[0][Number]</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/Legs_0_OnCallDuration__c.field-meta.xml
<CustomField>
    <fullName>Legs_0_OnCallDuration__c</fullName>
    <label>Legs[0][OnCallDuration]</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/Legs_0_Type__c.field-meta.xml
<CustomField>
    <fullName>Legs_0_Type__c</fullName>
    <label>Legs[0][Type]</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/OutgoingPhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>OutgoingPhoneNumber__c</fullName>
    <label>OutgoingPhoneNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/RecordingAvailableBy__c.field-meta.xml
<CustomField>
    <fullName>RecordingAvailableBy__c</fullName>
    <label>RecordingAvailableBy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/RecordingUrl__c.field-meta.xml
<CustomField>
    <fullName>RecordingUrl__c</fullName>
    <label>RecordingUrl</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/Schedule_Action__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Action__c</fullName>
    <label>Schedule Action</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>StartTime</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExotelRestResource.cls
/**
 * @File Name          : ExotelRestResource.cls
 * @Description        : 
 * @Author             : Kunal
 * @Group              : 
 * @Last Modified By   : Kunal
 * @Last Modified On   : 13/04/2020, 12:26:23 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    13/04/2020           Kunal              Initial Version
**/
@RestResource(urlMapping='/ExotelLead')
global class ExotelRestResource {
   
   
    @HttpGet
    global static void getLead(){
        RestRequest req = RestContext.request;
        RestResponse res = Restcontext.response;
        System.debug('URL: '+req.requestURI);
        Map <String, String> reqparams = req.params;
        System.debug('reqparams: '+reqparams) ;
        Exotel_Call_Summary__c ecs = new Exotel_Call_Summary__c();
        for(String strKey : reqparams.keySet()){
            System.debug(strKey +' : '+reqparams.get(strKey));
            if(strKey == 'CallFrom')
            	ecs.CallFrom__c = reqparams.get(strKey);
            if(strKey == 'CallSid')
                ecs.CallSid__c = reqparams.get(strKey);
            if(strKey == 'CallTo')
            	ecs.CallTo__c = reqparams.get(strKey);
            if(strKey == 'CallType')
            	ecs.CallType__c = reqparams.get(strKey);
            if(strKey == 'Created')
            	ecs.Created__c = reqparams.get(strKey);
            if(strKey == 'CurrentTime')
            	ecs.CurrentTime__c = reqparams.get(strKey);
            if(strKey == 'DialCallDuration')
            	ecs.DialCallDuration__c = reqparams.get(strKey);
            if(strKey == 'DialCallStatus')
            	ecs.DialCallStatus__c = reqparams.get(strKey);
            if(strKey == 'DialWhomNumber')
            	ecs.DialWhomNumber__c = reqparams.get(strKey);
            if(strKey == 'Direction')
            	ecs.Direction__c = reqparams.get(strKey);
            if(strKey == 'EndTime')
            	ecs.EndTime__c = reqparams.get(strKey);
            if(strKey == 'flow_id')
            	ecs.Flow_Id__c = reqparams.get(strKey);
            if(strKey == 'From')
            	ecs.From__c = reqparams.get(strKey);
            if(strKey == 'Legs[0][Cause]')
            	ecs.Legs_0_Cause__c = reqparams.get(strKey);
            if(strKey == 'Legs[0][CauseCode]')
            	ecs.Legs_0_CauseCode__c = reqparams.get(strKey);
            if(strKey == 'Legs[0][Number]')
            	ecs.Legs_0_Number__c = reqparams.get(strKey);
            if(strKey == 'Legs[0][OnCallDuration]')
            	ecs.Legs_0_OnCallDuration__c = reqparams.get(strKey);
            if(strKey == 'Legs[0][Type]')
            	ecs.Legs_0_Type__c = reqparams.get(strKey);
            if(strKey == 'OutgoingPhoneNumber')
            	ecs.OutgoingPhoneNumber__c = reqparams.get(strKey);
            if(strKey == 'RecordingAvailableBy')
            	ecs.RecordingAvailableBy__c = reqparams.get(strKey);
            if(strKey == 'RecordingUrl')
            	ecs.RecordingUrl__c = reqparams.get(strKey);
            if(strKey == 'StartTime')
            	ecs.StartTime__c = reqparams.get(strKey);
            if(strKey == 'tenant_id')
            	ecs.Tenant_Id__c = reqparams.get(strKey);
            if(strKey == 'To')
            	ecs.To__c = reqparams.get(strKey);
           ecs.Schedule_Action__c = system.now().addMinutes(5).addHours(-1);
        }
        insert ecs;  
    }
}