force-app/main/default/objects/Exotel_Call_Summary__c/Exotel_Call_Summary__c.object-meta.xml
<CustomObject>
    <label>Exotel Call Summary</label>
    <nameField>
        <displayFormat>ECS-{0000}</displayFormat>
        <label>Exotel Call Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exotel Call Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exotel_Call_Summary__c/fields/Exotel_Callout__c.field-meta.xml
<CustomField>
    <fullName>Exotel_Callout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exotel Callout</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ExotelCallSummaryTriggerHandler.cls
public class ExotelCallSummaryTriggerHandler {
    public static void onAfterInsert(list<Exotel_Call_Summary__c> ecslist){
        list<Exotel_Call_Summary__c> ecsleadlist =new list<Exotel_Call_Summary__c>();
        
        for(Exotel_Call_Summary__c ecs : ecslist){
            ecsleadlist.add(ecs);
        }
        
        system.debug('ecsleadlist'+ecsleadlist);
        if(!ecsleadlist.isEmpty()){
            ExotelCallSummaryTriggerHelper.createLeadRecord(ecsleadlist);
        }         
    }
    
    public static void onAfterUpdate(List<Exotel_Call_Summary__c> newList, Map<Id, Exotel_Call_Summary__c> oldMap){
        Set<Id> exotelIds = new Set<Id>();
        for(Exotel_Call_Summary__c ecs : newList){
            if(ecs.Exotel_Callout__c != oldMap.get(ecs.Id).Exotel_callout__c && ecs.Exotel_Callout__c == true){
                exotelIds.add(ecs.Id);
            }
        }
        System.debug('exotelIds '+exotelIds);
        if(!exotelIds.isEmpty()){
            ExotelCallout.sendExotelInfo(exotelIds);
        }
    }
    
    @invocableMethod
    public static void callHelper(List<Id> exotel_ids){
        Set<Id> eIds = new Set<Id>();
        for(Id i : exotel_ids){
            eIds.add(i);
        }
        
        System.debug('Eids '+eIds);
        if(!eIds.isEmpty()){
            ExotelCallSummaryTriggerHelper.callExotelCallout(eIds);
        }
    }

}